In [ ]:
!pip install pandas

Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2026.3)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
import os
import ast
import pandas as pd

In [ ]:
BASE_PATH = "/content/drive/MyDrive/AI-Placement-Copilot-ML"

matched_jobs_path = os.path.join(
    BASE_PATH,
    "outputs",
    "matched_jobs.csv"
)

output_path = os.path.join(
    BASE_PATH,
    "outputs"
)

In [ ]:
df = pd.read_csv(matched_jobs_path)

print("Total Records:", len(df))
df.head()

Total Records: 1120

,Resume,Resume Skills,Job Title,Company,Location,Required Skills,Similarity Score
0,KY BA PM UPDATED RESUME .docx,"['C', 'SQL']",Senior Software Engineer (multiple position),GE Digital,"Foxborough, MA","Software Engineering, Scrum, Agile, TDD, BDD, ...",0.598232
1,KY BA PM UPDATED RESUME .docx,"['C', 'SQL']",Senior Application Software Engineer (Web Serv...,Get It Recruit - Information Technology,"Beverly Hills, MI","Java, C#, Node.js, MongoDB, React, Software De...",0.632962
2,KY BA PM UPDATED RESUME .docx,"['C', 'SQL']",Software Engineer,DUAL North America,"Charlotte, NC","Software Development Life Cycle (SDLC), Softwa...",0.634471
3,KY BA PM UPDATED RESUME .docx,"['C', 'SQL']",Principal Software Engineer,"AvidXchange, Inc.","Charlotte, NC",".NET Core, .NET Framework 4.5+, C#, JavaScript...",0.636203
4,KY BA PM UPDATED RESUME .docx,"['C', 'SQL']",Senior Software Engineer,"The Timberline Group, LLC","St Louis, MO","Software Engineering, Agile Scrum SDLC, Integr...",0.643244

In [ ]:
def convert_resume_skills(text):

    if pd.isna(text):
        return []

    try:
        return ast.literal_eval(text)
    except:
        return []


def convert_job_skills(text):

    if pd.isna(text):
        return []

    return [
        skill.strip()
        for skill in str(text).split(",")
        if skill.strip()
    ]


df["Resume Skills"] = df["Resume Skills"].apply(convert_resume_skills)

df["Required Skills"] = df["Required Skills"].apply(convert_job_skills)

In [ ]:
resources = {

    "python":"Python for Everybody (Coursera)",

    "java":"Java Programming (Udemy)",

    "sql":"SQLBolt",

    "aws":"AWS Skill Builder",

    "docker":"Docker Official Docs",

    "react":"React Official Docs",

    "mongodb":"MongoDB University",

    "tensorflow":"TensorFlow Tutorials",

    "pytorch":"PyTorch Tutorials",

    "git":"GitHub Learning Lab",

    "linux":"Linux Journey",

    "machine learning":"Andrew Ng ML Course",

    "deep learning":"Deep Learning Specialization",

    "fastapi":"FastAPI Documentation"

}

In [ ]:
results = []

for _, row in df.iterrows():

    resume = {x.lower().strip() for x in row["Resume Skills"]}

    required = {x.lower().strip() for x in row["Required Skills"]}

    matched = sorted(resume & required)

    missing = sorted(required - resume)

    if len(required) == 0:
        percentage = 0
    else:
        percentage = round(
            (len(matched)/len(required))*100,
            2
        )

    if percentage >= 80:
        strength = "Excellent"

    elif percentage >= 60:
        strength = "Good"

    elif percentage >= 40:
        strength = "Average"

    else:
        strength = "Needs Improvement"

    learning = []

    for skill in missing:

        learning.append(
            resources.get(
                skill,
                f"Learn {skill.title()} from Coursera/Udemy"
            )
        )

    if percentage >= 80:
        priority = "Low"

    elif percentage >= 60:
        priority = "Medium"

    else:
        priority = "High"

    results.append({

        "Resume": row["Resume"],

        "Job Title": row["Job Title"],

        "Company": row["Company"],

        "Similarity Score": row["Similarity Score"],

        "Skill Match %": percentage,

        "Resume Strength": strength,

        "Matched Skills": ", ".join(matched),

        "Missing Skills": ", ".join(missing),

        "Learning Recommendation": " | ".join(learning),

        "Learning Priority": priority

    })

In [ ]:
skill_gap = pd.DataFrame(results)

skill_gap.head()

,Resume,Job Title,Company,Similarity Score,Skill Match %,Resume Strength,Matched Skills,Missing Skills,Learning Recommendation,Learning Priority
0,KY BA PM UPDATED RESUME .docx,Senior Software Engineer (multiple position),GE Digital,0.598232,2.86,Needs Improvement,sql,"agile, asp.net, asset performance management (...",Learn Agile from Coursera/Udemy | Learn Asp.Ne...,High
1,KY BA PM UPDATED RESUME .docx,Senior Application Software Engineer (Web Serv...,Get It Recruit - Information Technology,0.632962,0.00,Needs Improvement,,"agile methodology, c#, documentation, java, mo...",Learn Agile Methodology from Coursera/Udemy | ...,High
2,KY BA PM UPDATED RESUME .docx,Software Engineer,DUAL North America,0.634471,0.00,Needs Improvement,,".net, agile, angular, azure, c#, cosmos, java,...",Learn .Net from Coursera/Udemy | Learn Agile f...,High
3,KY BA PM UPDATED RESUME .docx,Principal Software Engineer,"AvidXchange, Inc.",0.636203,2.50,Needs Improvement,sql,".net core, .net framework 4.5+, agile, apis, a...",Learn .Net Core from Coursera/Udemy | Learn .N...,High
4,KY BA PM UPDATED RESUME .docx,Senior Software Engineer,"The Timberline Group, LLC",0.643244,0.00,Needs Improvement,,"agile scrum sdlc, api development, aws, c# .ne...",Learn Agile Scrum Sdlc from Coursera/Udemy | L...,High

In [ ]:
skill_gap = skill_gap.sort_values(
    by=["Skill Match %","Similarity Score"],
    ascending=False
)

skill_gap.head(20)

,Resume,Job Title,Company,Similarity Score,Skill Match %,Resume Strength,Matched Skills,Missing Skills,Learning Recommendation,Learning Priority
909,Sougandh_Java Fullstack Developer.docx,Java Software Engineer - Remote,Get It Recruit - Information Technology,0.623725,61.54,Good,"css, git, html, java, javascript, linux, react...","agile, angular, nosql, restful api, spring boot",Learn Agile from Coursera/Udemy | Learn Angula...,Medium
617,Pranay P.docx,Java Software Engineer - Remote,Get It Recruit - Information Technology,0.730628,53.85,Average,"css, git, html, java, javascript, react, sql","agile, angular, linux, nosql, restful api, spr...",Learn Agile from Coursera/Udemy | Learn Angula...,High
412,Venkata_Sr.PHP_Developer.docx,Software Engineer,Omni Federal,0.698210,50.00,Average,"css, git, html, linux, mysql","agile (safe), java server pages (jsp), javascr...",Learn Agile (Safe) from Coursera/Udemy | Learn...,High
429,sai k.docx,Java Software Engineer - Remote,Get It Recruit - Information Technology,0.638589,46.15,Average,"css, git, html, java, javascript, sql","agile, angular, linux, nosql, react, restful a...",Learn Agile from Coursera/Udemy | Learn Angula...,High
651,Resume2018March.docx,Software Engineer - PHP,Spectrum IT Recruitment,0.788846,40.00,Average,"css, html, javascript, mysql","api, cloud platform, computer science, php, pr...",Learn Api from Coursera/Udemy | Learn Cloud Pl...,High
524,Sravani Singirikonda.docx,Python-Django-React- MaterialUI Fullsctack Sof...,IT Crowd,0.670062,38.46,Needs Improvement,"aws, docker, mysql, node.js, python","agile methodologies, ci/cd, django, etl, mater...",Learn Agile Methodologies from Coursera/Udemy ...,High
899,avinash G.docx,Software Developer - Full Stack - Senior,J&M Group,0.732114,37.50,Needs Improvement,"aws, css, git, html, java, react","agile, angular js, figma, github, jamstack, ji...",Learn Agile from Coursera/Udemy | Learn Angula...,High
587,sairithvik alla.docx,Software Developer - Full Stack - Senior,J&M Group,0.728730,37.50,Needs Improvement,"aws, css, git, html, java, react","agile, angular js, figma, github, jamstack, ji...",Learn Agile from Coursera/Udemy | Learn Angula...,High
749,nithin Reddy.docx,Software Developer - Full Stack - Senior,J&M Group,0.724706,37.50,Needs Improvement,"aws, css, git, html, java, react","agile, angular js, figma, github, jamstack, ji...",Learn Agile from Coursera/Udemy | Learn Angula...,High
523,Sravani Singirikonda.docx,Software Developer - Full Stack - Senior,J&M Group,0.669894,37.50,Needs Improvement,"aws, css, git, html, java, react","agile, angular js, figma, github, jamstack, ji...",Learn Agile from Coursera/Udemy | Learn Angula...,High
1039,Vivek.BSA.docx,Software Developer,Chenega Corporation,0.763159,33.33,Needs Improvement,"css, html, java, javascript, sql","agile methodology, continuous integration/cont...",Learn Agile Methodology from Coursera/Udemy | ...,High
307,Anil Krishna Mogalaturthi.docx,Software Engineer,Infinite Computer Solutions,0.411107,31.82,Needs Improvement,"css, docker, html, java, kubernetes, react, sql","ai, caching, cloud technologies, gcp, json, ku...",Learn Ai from Coursera/Udemy | Learn Caching f...,High
328,Uday_Maripelly.docx,Software Development Engineer,Peer Consulting Resources Inc.,0.546812,31.58,Needs Improvement,"css, git, html, java, javascript, sql","analytical skills, appium, ci/cd, cypress, git...",Learn Analytical Skills from Coursera/Udemy | ...,High
665,Vinay.D_Resume.docx,Software Developer,Minden Medical Center,0.453127,31.25,Needs Improvement,"css, docker, html, javascript, react","aws certification, aws lambda, aws services, c...",Learn Aws Certification from Coursera/Udemy | ...,High
122,Jennifer M. Conte.docx,Software Developer JAVA/SQL (multiple positions),"Trinity Technology Partners, Inc.",0.772454,30.77,Needs Improvement,"c, java, javascript, sql","ant, eclipse, ewm, jboss, maven, microsoft sui...",Learn Ant from Coursera/Udemy | Learn Eclipse ...,High
862,jeck P.docx,Software Developer JAVA/SQL (multiple positions),"Trinity Technology Partners, Inc.",0.719660,30.77,Needs Improvement,"c, java, javascript, sql","ant, eclipse, ewm, jboss, maven, microsoft sui...",Learn Ant from Coursera/Udemy | Learn Eclipse ...,High
1073,Randy Adams.docx,Software Developer JAVA/SQL (multiple positions),"Trinity Technology Partners, Inc.",0.683517,30.77,Needs Improvement,"c, java, javascript, sql","ant, eclipse, ewm, jboss, maven, microsoft sui...",Learn Ant from Coursera/Udemy | Learn Eclipse ...,High
100,Drakshajavauidev.docx,Software Developer JAVA/SQL (multiple positions),"Trinity Technology Partners, Inc.",0.608320,30.77,Needs Improvement,"c, java, javascript, sql","ant, eclipse, ewm, jboss, maven, microsoft sui...",Learn Ant from Coursera/Udemy | Learn Eclipse ...,High
873,ravikiran JALASUTRAPU.docx,Java Software Engineer,"TalentBurst, an Inc 5000 company",0.572642,30.77,Needs Improvement,"java, javascript, mongodb, sql","cake, drupal, kotlin, php, python, ruby, sprin...",Learn Cake from Coursera/Udemy | Learn Drupal ...,High
866,Tarun_Developer.docx,Software Developer JAVA/SQL (multiple positions),"Trinity Technology Partners, Inc.",0.537569,30.77,Needs Improvement,"c, java, javascript, sql","ant, eclipse, ewm, jboss, maven, microsoft sui...",Learn Ant from Coursera/Udemy | Learn Eclipse ...,High

In [ ]:
skill_gap.to_csv(
    os.path.join(output_path,"skill_gap.csv"),
    index=False
)

print("Skill Gap Analysis Saved Successfully!")

Skill Gap Analysis Saved Successfully!

In [ ]:
print("="*50)
print("AI SKILL GAP ANALYSIS SUMMARY")
print("="*50)

print("Total Recommendations :", len(skill_gap))

print("Average Skill Match :",
      round(skill_gap["Skill Match %"].mean(),2),
      "%")

print("\nResume Strength Distribution")

print(skill_gap["Resume Strength"].value_counts())

print("\nTop 10 Best Matches")

display(skill_gap.head(10))

==================================================
AI SKILL GAP ANALYSIS SUMMARY
==================================================
Total Recommendations : 1120
Average Skill Match : 9.84 %

Resume Strength Distribution
Resume Strength
Needs Improvement    1115
Average                 4
Good                    1
Name: count, dtype: int64

Top 10 Best Matches

,Resume,Job Title,Company,Similarity Score,Skill Match %,Resume Strength,Matched Skills,Missing Skills,Learning Recommendation,Learning Priority
909,Sougandh_Java Fullstack Developer.docx,Java Software Engineer - Remote,Get It Recruit - Information Technology,0.623725,61.54,Good,"css, git, html, java, javascript, linux, react...","agile, angular, nosql, restful api, spring boot",Learn Agile from Coursera/Udemy | Learn Angula...,Medium
617,Pranay P.docx,Java Software Engineer - Remote,Get It Recruit - Information Technology,0.730628,53.85,Average,"css, git, html, java, javascript, react, sql","agile, angular, linux, nosql, restful api, spr...",Learn Agile from Coursera/Udemy | Learn Angula...,High
412,Venkata_Sr.PHP_Developer.docx,Software Engineer,Omni Federal,0.698210,50.00,Average,"css, git, html, linux, mysql","agile (safe), java server pages (jsp), javascr...",Learn Agile (Safe) from Coursera/Udemy | Learn...,High
429,sai k.docx,Java Software Engineer - Remote,Get It Recruit - Information Technology,0.638589,46.15,Average,"css, git, html, java, javascript, sql","agile, angular, linux, nosql, react, restful a...",Learn Agile from Coursera/Udemy | Learn Angula...,High
651,Resume2018March.docx,Software Engineer - PHP,Spectrum IT Recruitment,0.788846,40.00,Average,"css, html, javascript, mysql","api, cloud platform, computer science, php, pr...",Learn Api from Coursera/Udemy | Learn Cloud Pl...,High
524,Sravani Singirikonda.docx,Python-Django-React- MaterialUI Fullsctack Sof...,IT Crowd,0.670062,38.46,Needs Improvement,"aws, docker, mysql, node.js, python","agile methodologies, ci/cd, django, etl, mater...",Learn Agile Methodologies from Coursera/Udemy ...,High
899,avinash G.docx,Software Developer - Full Stack - Senior,J&M Group,0.732114,37.50,Needs Improvement,"aws, css, git, html, java, react","agile, angular js, figma, github, jamstack, ji...",Learn Agile from Coursera/Udemy | Learn Angula...,High
587,sairithvik alla.docx,Software Developer - Full Stack - Senior,J&M Group,0.728730,37.50,Needs Improvement,"aws, css, git, html, java, react","agile, angular js, figma, github, jamstack, ji...",Learn Agile from Coursera/Udemy | Learn Angula...,High
749,nithin Reddy.docx,Software Developer - Full Stack - Senior,J&M Group,0.724706,37.50,Needs Improvement,"aws, css, git, html, java, react","agile, angular js, figma, github, jamstack, ji...",Learn Agile from Coursera/Udemy | Learn Angula...,High
523,Sravani Singirikonda.docx,Software Developer - Full Stack - Senior,J&M Group,0.669894,37.50,Needs Improvement,"aws, css, git, html, java, react","agile, angular js, figma, github, jamstack, ji...",Learn Agile from Coursera/Udemy | Learn Angula...,High